on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: smartinvoiceprocessing.azurecr.io
        username: ${{ secrets.acr_smartinvoiceprocessing_username }}
        password: ${{ secrets.acr_smartinvoiceprocessing_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t smartinvoiceprocessing.azurecr.io/sipdevk8s:${{ github.sha }}
        docker push smartinvoiceprocessing.azurecr.io/sipdevk8s:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_sipdevk8s_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep peopleplatformf1af | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace peopleplatformf1af`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: peopleplatformf1af
        container-registry-url: smartinvoiceprocessing.azurecr.io
        container-registry-username: ${{ secrets.acr_smartinvoiceprocessing_username }}
        container-registry-password: ${{ secrets.acr_smartinvoiceprocessing_password }}
        secret-name: sipdevk8sdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: peopleplatformf1af
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          smartinvoiceprocessing.azurecr.io/sipdevk8s:${{ github.sha }}
        imagepullsecrets: |
          sipdevk8sdockerauth
